#name: Release workflow
#on:
# push:
#  branches:
#    - main
#  workflow_dispatch:
#
#jobs:
#  release-tag:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create Github release
#        id: create-new-release
#        uses: actions/create-release@v1
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#            tag_name: ${{ github.run_number }}
#            release_name: Release ${{ github.run_number }}
#      - name: Upload release asset
#        uses: actions/upload-release-asset@v1
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
#          asset_path: ./site.zip
#          asset_name: site-v${{ github.run_number}}.zip
#          asset_content_type: application/zip


name: Release workflow
on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@main
        with:
          bump_version_scheme: minor
          use_github_release_notes: true

