name: Release workflow
on:
 push:
  branches:
    - main
  workflow_dispatch:

jobs:
  release tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
      - name: Create Github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
